;;;; ABOUTME: Deployment utilities for quickapi - generates scripts for production deployment

(in-package :quickapi)

;;; Route introspection for script generation

(defun get-registered-routes ()
  "Return a list of all registered routes as plists.
   Each plist contains :method :pattern :resource-name"
  (let ((routes nil))
    (maphash (lambda (key entry)
               (declare (ignore key))
               (push (list :method (route-entry-method entry)
                           :pattern (route-entry-pattern entry)
                           :resource-name (route-entry-resource-name entry))
                     routes))
             *route-registry*)
    (nreverse routes)))

;;; Smoke Test Generation

(defun generate-smoke-tests (&key (stream *standard-output*)
                                  (base-url "http://localhost:8000")
                                  (api-name "api"))
  "Generate a bash script for smoke testing the API.
   Outputs curl commands for each registered route.
   For authenticated routes, includes placeholder for JWT token."
  (format stream "#!/bin/bash~%")
  (format stream "# Smoke tests for ~A~%" api-name)
  (format stream "# Generated by quickapi~%")
  (format stream "# Run: chmod +x smoke-tests.sh && ./smoke-tests.sh~%~%")
  (format stream "set -e~%~%")
  (format stream "BASE_URL=\"${API_URL:-~A}\"~%" base-url)
  (format stream "TOKEN=\"${JWT_TOKEN:-}\"~%")
  (format stream "FAILED=0~%")
  (format stream "PASSED=0~%~%")

  (format stream "# Colors for output~%")
  (format stream "RED='\\033[0;31m'~%")
  (format stream "GREEN='\\033[0;32m'~%")
  (format stream "NC='\\033[0m' # No Color~%~%")

  (format stream "test_endpoint() {~%")
  (format stream "    local method=$1~%")
  (format stream "    local endpoint=$2~%")
  (format stream "    local expected_status=$3~%")
  (format stream "    local data=$4~%")
  (format stream "    local auth=$5~%~%")
  (format stream "    local auth_header=\"\"~%")
  (format stream "    if [ -n \"$auth\" ] && [ -n \"$TOKEN\" ]; then~%")
  (format stream "        auth_header=\"-H \\\"Authorization: Bearer $TOKEN\\\"\"~%")
  (format stream "    fi~%~%")
  (format stream "    local data_arg=\"\"~%")
  (format stream "    if [ -n \"$data\" ]; then~%")
  (format stream "        data_arg=\"-d '$data'\"~%")
  (format stream "    fi~%~%")
  (format stream "    local status~%")
  (format stream "    status=$(eval curl -s -o /dev/null -w '%{http_code}' \\~%")
  (format stream "        -X $method \\~%")
  (format stream "        -H 'Content-Type: application/json' \\~%")
  (format stream "        $auth_header \\~%")
  (format stream "        $data_arg \\~%")
  (format stream "        \"$BASE_URL$endpoint\")~%~%")
  (format stream "    if [ \"$status\" = \"$expected_status\" ]; then~%")
  (format stream "        echo -e \"${GREEN}✓${NC} $method $endpoint -> $status\"~%")
  (format stream "        ((PASSED++))~%")
  (format stream "    else~%")
  (format stream "        echo -e \"${RED}✗${NC} $method $endpoint -> $status (expected $expected_status)\"~%")
  (format stream "        ((FAILED++))~%")
  (format stream "    fi~%")
  (format stream "}~%~%")

  (format stream "echo \"Running smoke tests against $BASE_URL\"~%")
  (format stream "echo \"==========================================\"~%~%")

  ;; Generate test for each route
  (let ((routes (get-registered-routes)))
    (if routes
        (dolist (route routes)
          (let* ((method (getf route :method))
                 (pattern (getf route :pattern))
                 ;; Replace :param with test value
                 (test-path (cl-ppcre:regex-replace-all ":[^/]+" pattern "1"))
                 (has-body (member method '(:post :put :patch)))
                 (sample-body (if has-body "{\\\"test\\\": true}" "")))
            (format stream "test_endpoint ~A ~A 200 \"~A\" \"\"~%"
                    (string-upcase (symbol-name method))
                    test-path
                    sample-body)))
        ;; No routes registered - provide example
        (progn
          (format stream "# No routes registered yet. Example tests:~%")
          (format stream "# test_endpoint GET /health 200 \"\" \"\"~%")
          (format stream "# test_endpoint POST /auth/login 200 '{\"email\":\"test@example.com\",\"password\":\"test\"}' \"\"~%")
          (format stream "# test_endpoint GET /todos 200 \"\" \"auth\"~%"))))

  (format stream "~%echo \"\"~%")
  (format stream "echo \"==========================================\"~%")
  (format stream "echo \"Passed: $PASSED, Failed: $FAILED\"~%")
  (format stream "~%if [ $FAILED -gt 0 ]; then~%")
  (format stream "    exit 1~%")
  (format stream "fi~%"))

;;; Systemd Unit Generation

(defun generate-systemd-unit (&key (stream *standard-output*)
                                   (api-name "my-api")
                                   (description "Common Lisp API Service")
                                   (user "www-data")
                                   (working-dir "/opt/api")
                                   (port 8000))
  "Generate a systemd service unit file for the API.
   Configures the service for production use with proper restart policies."
  (format stream "[Unit]~%")
  (format stream "Description=~A~%" description)
  (format stream "Documentation=https://github.com/your-org/~A~%" api-name)
  (format stream "After=network.target~%")
  (format stream "Wants=network-online.target~%~%")

  (format stream "[Service]~%")
  (format stream "Type=simple~%")
  (format stream "User=~A~%" user)
  (format stream "Group=~A~%" user)
  (format stream "WorkingDirectory=~A~%" working-dir)
  (format stream "~%")
  (format stream "# Environment~%")
  (format stream "EnvironmentFile=-~A/.env~%" working-dir)
  (format stream "Environment=PORT=~A~%" port)
  (format stream "~%")
  (format stream "# Start command - adjust path to your sbcl/quicklisp setup~%")
  (format stream "ExecStart=~A/bin/start~%" working-dir)
  (format stream "~%")
  (format stream "# Restart policy~%")
  (format stream "Restart=always~%")
  (format stream "RestartSec=5~%")
  (format stream "~%")
  (format stream "# Security hardening~%")
  (format stream "NoNewPrivileges=yes~%")
  (format stream "PrivateTmp=yes~%")
  (format stream "ProtectSystem=strict~%")
  (format stream "ProtectHome=yes~%")
  (format stream "ReadWritePaths=~A~%" working-dir)
  (format stream "~%")
  (format stream "# Logging~%")
  (format stream "StandardOutput=journal~%")
  (format stream "StandardError=journal~%")
  (format stream "SyslogIdentifier=~A~%~%" api-name)

  (format stream "[Install]~%")
  (format stream "WantedBy=multi-user.target~%"))

;;; Start Script Generation

(defun generate-start-script (&key (stream *standard-output*)
                                   (system-name "my-api")
                                   (entry-point "start-api"))
  "Generate a bash script to start the API server.
   Uses sbcl with quicklisp to load and start the system."
  (format stream "#!/bin/bash~%")
  (format stream "# Start script for ~A~%" system-name)
  (format stream "# Generated by quickapi~%~%")
  (format stream "set -e~%~%")
  (format stream "# Configuration~%")
  (format stream "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"~%")
  (format stream "PROJECT_DIR=\"$(dirname \"$SCRIPT_DIR\")\"~%")
  (format stream "SYSTEM_NAME=\"~A\"~%" system-name)
  (format stream "~%")
  (format stream "# Load .env if present~%")
  (format stream "if [ -f \"$PROJECT_DIR/.env\" ]; then~%")
  (format stream "    set -a~%")
  (format stream "    source \"$PROJECT_DIR/.env\"~%")
  (format stream "    set +a~%")
  (format stream "fi~%~%")
  (format stream "# Default values~%")
  (format stream "PORT=\"${PORT:-8000}\"~%")
  (format stream "HOST=\"${HOST:-0.0.0.0}\"~%~%")
  (format stream "cd \"$PROJECT_DIR\"~%~%")
  (format stream "# Start the server~%")
  (format stream "exec sbcl --non-interactive \\~%")
  (format stream "    --eval \"(require :asdf)\" \\~%")
  (format stream "    --eval \"(push #P\\\"$PROJECT_DIR/\\\" asdf:*central-registry*)\" \\~%")
  (format stream "    --eval \"(asdf:load-system :$SYSTEM_NAME)\" \\~%")
  (format stream "    --eval \"(~A:~A :port $PORT :address \\\"$HOST\\\")\" \\~%"
          system-name entry-point)
  (format stream "    --eval \"(loop (sleep 86400))\"~%"))

;;; Healthcheck Script Generation

(defun generate-healthcheck (&key (stream *standard-output*)
                                  (base-url "http://localhost:8000")
                                  (endpoint "/health"))
  "Generate a healthcheck script for monitoring."
  (format stream "#!/bin/bash~%")
  (format stream "# Healthcheck script~%")
  (format stream "# Generated by quickapi~%~%")
  (format stream "BASE_URL=\"${API_URL:-~A}\"~%" base-url)
  (format stream "ENDPOINT=\"~A\"~%~%" endpoint)
  (format stream "response=$(curl -s -o /dev/null -w '%%{http_code}' \"$BASE_URL$ENDPOINT\" 2>/dev/null)~%~%")
  (format stream "if [ \"$response\" = \"200\" ]; then~%")
  (format stream "    echo \"OK\"~%")
  (format stream "    exit 0~%")
  (format stream "else~%")
  (format stream "    echo \"FAIL: HTTP $response\"~%")
  (format stream "    exit 1~%")
  (format stream "fi~%"))

;;; Generate All Deployment Files

(defun generate-deployment-files (&key (directory ".")
                                       (system-name "my-api")
                                       (api-name "My API")
                                       (port 8000))
  "Generate all deployment files in the specified directory.
   Creates: bin/start, bin/healthcheck, scripts/smoke-tests.sh,
            scripts/app.service, .env.example"
  (let ((bin-dir (merge-pathnames "bin/" directory))
        (scripts-dir (merge-pathnames "scripts/" directory)))

    ;; Ensure directories exist
    (ensure-directories-exist bin-dir)
    (ensure-directories-exist scripts-dir)

    ;; Generate bin/start
    (with-open-file (s (merge-pathnames "start" bin-dir)
                       :direction :output
                       :if-exists :supersede)
      (generate-start-script :stream s
                             :system-name system-name
                             :entry-point "start-api"))

    ;; Generate bin/healthcheck
    (with-open-file (s (merge-pathnames "healthcheck" bin-dir)
                       :direction :output
                       :if-exists :supersede)
      (generate-healthcheck :stream s
                            :base-url (format nil "http://localhost:~A" port)))

    ;; Generate scripts/smoke-tests.sh
    (with-open-file (s (merge-pathnames "smoke-tests.sh" scripts-dir)
                       :direction :output
                       :if-exists :supersede)
      (generate-smoke-tests :stream s
                            :base-url (format nil "http://localhost:~A" port)
                            :api-name api-name))

    ;; Generate scripts/app.service
    (with-open-file (s (merge-pathnames (format nil "~A.service" system-name) scripts-dir)
                       :direction :output
                       :if-exists :supersede)
      (generate-systemd-unit :stream s
                             :api-name system-name
                             :description api-name
                             :port port))

    ;; Generate .env.example
    (with-open-file (s (merge-pathnames ".env.example" directory)
                       :direction :output
                       :if-exists :supersede)
      (print-env-template nil :stream s))

    (format t "Generated deployment files:~%")
    (format t "  ~A~%" (merge-pathnames "start" bin-dir))
    (format t "  ~A~%" (merge-pathnames "healthcheck" bin-dir))
    (format t "  ~A~%" (merge-pathnames "smoke-tests.sh" scripts-dir))
    (format t "  ~A~%" (merge-pathnames (format nil "~A.service" system-name) scripts-dir))
    (format t "  ~A~%" (merge-pathnames ".env.example" directory))
    (format t "~%Don't forget to: chmod +x bin/* scripts/*.sh~%")
    t))
